### PR TITLE
Adds Varnish pluging

### PR DESCRIPTION
**Pull request by luisdavim**

### CODE REVIEW

**Comment by jonlives** [comment]
Hi Luis,

Thanks for the PR!  Could I ask that you please rebase your local copy from origin/master and resubmit this please? It's pulled in a bunch of older commits etc along with your own commit. It'll just keep the commit history tidier and easier to follow :)

**Comment by luisdavim** [comment]
Hi Jon,

Sorry about that. I've rebased my fork from your master, does it look better now?

**Comment by jonlives** [comment]
@luisdavim much better thanks! Are y'all using the varnish plugin in anger at the moment? I don't have anything I can test that against currently so just checking if it's currently "known good" :p

**Comment by luisdavim** [comment]
Yes, we are using it, we use ipecache with both CloudFront and Varnish plugins to invalidate the images that we update on our CDN servers.

**Comment by jonlives** [comment]
Awesome, great to hear. I'll get this merged and cut a new release as soon as poss :)

**Comment by luisdavim** [comment]
Awesome. Thanks.

**Comment by jonlives** [comment]
Just released version 0.0.12 with this included. Thanks!

**Pull request merged**
